### ISSUE TITLE
テキストでレンダリングする機能を実装する

### ISSUE THREAD

**Issue by ikeda-yuko** [nomlab/jay#2]
インデントが深すぎるため，2文字程度に浅くする必要がある．
指定した文字数で改行する必要がある．このとき，先頭にきてはいけない文字があった場合，1文字多く取る．
Markdown を テキストにレンダリングする仕組みがある．

**Comment by okada-takuya** [comment]
* 2015/06/29時点の方針
  * JayFlavoredMarkdownConverter と似た JayFlavoredMarkdownToPlainTextConverter を作成する．
  * pipeline では， JayAddLabelToListItems, JayAddCrossReference を実行し，その後の text をうまいこと改行処理する．

* やったことまとめ
  * pandoc の markdown to plain でどの程度うまく変換できるか確認した．
    * わかち書きしないと--columnsで改行が働かない．
    * そもそも出力がなんか微妙

**Comment by ikeda-yuko** [comment]
追加で発生した問題は別 issue とする．
本 issue に関しては #15 が merge したため close する．
