### ISSUE TITLE
Fluentdのセットアップを行う

### ISSUE THREAD

**Issue by ikeda-yuko** [nomlab/jay#29]
seiryuでFluentdのセットアップを行う．

**Comment by yoshida564** [comment]
fluentdのセットアップに際して，
まず，seiryuにnomlabユーザを作成し，ホームディレクトリ以下にfluentdディレクトリを作成した．

次に，bundlerを用いてfluentdのinstallを行った．
具体的には以下のコマンドを実行した．
`$ rbenv local 2.2.3`
`$ gem install bundler`
`$ bundle init`
`$ echo "gem 'fluentd'" >> Gemfile`
`$ bundle config build.fluentd —no-ri —nordoc`
`$ bundle install —path vendor/bundle`

また，fluentdのセットアップ，起動，および確認を行った．
具体的には以下のコマンドを実行した.
fluentdの設定ファイルを含むfluentディレクトリを作成
`$ bundle exec fluentd --setup ./fluent`
fluentdの起動
`$ bundle exec fluentd -c ./fluent/fluent.conf -vv &`
テストを行い，{“json”:”message”}が返ってくることを確認
`$ echo '{"json":"message"}' | bundle exec fluent-cat debug.test`

**Comment by yoshida564** [comment]
第117回GN談話会の議論を受けて，セットアップ方法を以下のように変更した．
+ bundle install 時に binstubs オプションを用いて，実行ファイルを /home/nomlab/fluentd/bin 以下に配置
+ daemon化して起動

/home/nomlab/fluentdディレクトリで，bundlerを用いてfluentdのinstallを行った．
具体的には以下のコマンドを実行した．
`$ rbenv local 2.2.3`
`$ gem install bundler`
`$ bundle init`
`$ echo "gem 'fluentd'" >> Gemfile`
`$ bundle config build.fluentd —no-ri —nordoc`
`$ bundle install —path vendor/bundle --binstubs`
`$ echo "export PATH='$HOME/fluentd/bin:$PATH'" >> /home/nomlab/.bash_profile`

また，fluentdのセットアップ，起動を行った．
具体的には以下のコマンドを実行した.
fluentdの設定ファイルを含むfluentディレクトリを作成
`$ fluentd --setup ./fluent`
fluentdの起動(daemon化)
`$ fluentd -c ./fluent/fluent.conf -d ./fluent/fluentd.pid`
daemon起動に必要となるpidファイルはfluent/fulentd.pidで作成

**Comment by emi0910** [comment]
議論の結果，問題ないため close します．
