### ISSUE TITLE
Fluentdの設定を行う

### ISSUE THREAD

**Issue by ikeda-yuko** [nomlab/jay#33]
Created from [AI0020](http://jay.swlab.cs.okayama-u.ac.jp/minutes/107?ai=0020) of minute 107.
以下の2点を設定する
* jay からの POST を受け入れ可能にする
* Lastnote にデータを転送する

**Comment by ikeda-yuko** [comment]
#### jay からの POST を受け入れ可能にする
fluentd の input plugin に http plugin を使用するように設定した．
具体的な設定ファイル( fluent.conf )の内容は [fluent.con](https://gist.github.com/ikeda-yuko/dfc8dedf704386b4ceb4) を参照．
port はデフォルトの 8888 であり，POST するときの url は以下の通りである．
`kawasemi.swlab.cs.okayama-u.ac.jp:8888`

#### Lastnote にデータを転送する
現在，Lastnote にデータを転送する create_lastnote_document output plugin を作成中である．
コードは [create_lastnote_document](https://gist.github.com/ikeda-yuko/2f449e2c601187658bac) を参照．

#### 気になること
##### 1. Lastnote に http リクエストを送るとき，ファイルを添付することが手間
Ruby の net/http モジュールを利用して http リクエストを送るよう実装しているが，
ファイルを添付する実装に非常に手間がかかる．

##### 2. Lastnote への POST が成功したときの返却コードが 302
document の POST が成功したとき，返却コードとして 302 (リダイレクト) が返ってくる．
既に存在する document に続けて POSTしたときは，返却コードとして 200 (成功) が返ってくる．

#### 問題点
##### 1. jay の minutes と Lastnote の document の要素が違う
具体的には Lastnote の document を作成するとき，以下の要素が足りない．
* category
* document_code
* project_id
現在の実装は，category は議事録で決め打ち，
document_code は "jay-" + jay上のminutesのid，project_idは，4 (乃村研) である．

##### 2. Lastnote の認証に Lastnote に存在するユーザの学籍番号が必要
Lastnote の認証は，学籍番号と token で行われる．
また，このとき利用した学籍番号が Lastnote の document の auther となる．
このため，minutes の auther の学籍番号で認証しなければならないが，
学籍番号の情報が jay に存在しない．

**Comment by yoshida564** [comment]
fluentd から LastNote に POST する際， minutes の author から学籍番号に変換できるようにした．
具体的には以下の変更を行った
- csv 形式で jay の screen name ，name，および学籍番号を記述した

csv ファイルの例は以下の通りである．
```screen_name,name,lastnote_number
yoshinari-nomura,YoshinariNomura,00000000
okada-takuya,TakuyaOkada,43426406
sugi-k,KeisukeSugi,09421624
ichikawa85,YuheiIchikawa,43427404
kitagaki,ChihiroKitagaki,43426413
...
```

- LastNote へ POST する際，csv ファイルを読み込み，screen name に対応する学籍番号を返す
- 対応する screen name が存在しなかった場合，SlackにPOSTできなかったことを通知する

なお，現在，jay から送られてくる JSON には author_id の情報しかないため，author_id に対応する user の screen name を生成する JSON に追加してほしい．

**Comment by ikeda-yuko** [comment]
fluentd から LastNote に POST する際， minutes の tag を category と project に変換するようにした．
具体的な実装は上記の学籍番号と同じである．

「tag」 と 「category，project」の対応は以下の通りである．
##### category
record → 記録書
minutes → 議事録
##### project
nomlab → 乃村研
gn → GN
new → New

また，jay から tags というキーで tag の配列が送られてくることを想定している．
category に対応する tag ，project に対応する tag がどちらか1つでもない場合，
lastnote への post は行わず，slack にその旨を通知する．

**Comment by ikeda-yuko** [comment]
fluentd が期待するデータの具体例は以下の通りである．
```
{
 "id":106,
 "title":"title",
 "dtstart":"2015-12-01T10:00:00.000Z",
 "dtend":"2015-12-01T10:00:00.000Z",
 "location":"104",
 "content":"content",
 "created_at":"2015-12-02T05:22:49.745Z",
 "updated_at":"2015-12-02T05:22:49.745Z",
 "name":"screen_name",
 "tags":["tag1, tag2"]
 }
````

また，以下の場合，lastnote への post は行わず，slack に通知する．
* 学籍番号 に対応する name がないとき
* category と project に対応する tags がないとき

**Comment by yoshida564** [comment]
post時のエラーを通知するBotをSlackBotからIncomming Webhooksに登録されているnomratに変更した．
通知するチャンネルは"#notifications"である．

**Comment by ikeda-yuko** [comment]
[第121回議事録](http://jay.swlab.cs.okayama-u.ac.jp/minutes/158)と[LastNoteのissue246のcomment](https://github.com/nomlab/LastNote/issues/246#issuecomment-187590262)を参考に
fluentd が Lastnote に post するときの body を以下のように変更した．
```
{
    "title": "第1回議事録",
    "description": "",
    "date": "2015-12-25",
    "category": "議事録",
    "document_code": "jay-001",
    "project": "GN",
    "previous_version": "",
    "star": false,
    "content": {
        "filename": "第1回議事録.txt",
        "content-type": "application/json",
        "blob": "44GT44KT44Gr44Gh44Gv77yM5LiW55WMCg=="
    }
}

```
