### ISSUE TITLE
jayのデザインを改善する(ページネーションや日付の表示)

### ISSUE THREAD

**Issue by emi0910** [nomlab/jay#56]
Created from [AI0142](http://jay.swlab.cs.okayama-u.ac.jp/minutes/261?ai=0142) of minute 261.
+ jayのデザインを改善する(ページネーションや日付の表示)．-->(市川 !:0142)

**Comment by ichikawa85** [comment]
# ページネーションについて
kaminariを用いて，ページネーションを行った．
しかし，tagで検索語，ページネーションできない．
今後はtag検索語，ページネーションできるようにすることを検討する．

# 日付の表示
検索語の日付の表示についてはAjaxの結果を変更することを検討している．
