### ISSUE TITLE
jayをrails5に移行する

### ISSUE THREAD

**Issue by emiksk** [nomlab/jay#57]
Created from [AI0143](http://jay.swlab.cs.okayama-u.ac.jp/minutes/261?ai=0143) of minute 261.
- jayをrails5に移行する．-->(吉田 !:0143)

**Comment by yoshida564** [comment]
# rails5に移行する手順
+ rubyのバージョンを2.2.2以上に変更
+ Gemfile内のrailsのバージョン指定を5.0.0に変更
+ `$ bundle update`
+ `$ bundle exec rails app:update`
  + 以下のファイルでコンフリクトするため，上書きするか選択(基本的には上書きするが，config/routes.rbとconfig/application.rbは上書きしない)
    +  config/boot.rb
    +  config/routes.rb
      + これは上書きしない
    +  config/application.rb
      + これは上書きしない
    + config/environment.rb
    + config/secrets.yml
    + config/environments/development.rb
    + config/environments/production.rb
    + config/environments/test.rb
    + config/initializers/cookies_serializer.rb
    + config/initializers/wrap_parameters.rb
    + bin/rails
    + bin/setup

#  rails5に移行後に確認したバグ
  + 議事録登録後に，編集で確認すると，2行目以降の各行の頭に18個の半角スペースが入る．

# 残された課題
+ rails5に合わせたコードの変更
+ 移行後に発生したバグの原因の特定

**Comment by yoshida564** [comment]
#62 のRPでは上記コメントのバグは解消したが，
残された課題として示しているrails5に合わせたコードの変更を行っていない．
