### ISSUE TITLE
議事録をテキスト形式でエクスポートする機能を実装する

### ISSUE THREAD

**Issue by emi0910** [nomlab/jay#58]
Created from [AI0144](http://jay.swlab.cs.okayama-u.ac.jp/minutes/261?ai=0144) of minute 261.
+ 議事録をテキスト形式でエクスポートする機能を実装する．-->(小林 !:0144)

**Comment by kobayashi1027** [comment]
議事録をテキスト形式でダウンロードする機能を実装した．
ダウンロード用のリンクを追加するにあたり，まず，Minuteのshowページに簡単なヘッダを追加した．
このヘッダにあるダウンロードアイコン(<img width="16" alt="download" src="https://cloud.githubusercontent.com/assets/7124058/18152644/47c3b5c8-7032-11e6-944c-1bdd716aecdc.png">)をクリックすることで，txt形式の議事録をダウンロードできる．

ただし，HTML5のdownload属性を使用して実装しているため，これをサポートしていないブラウザでは動作しない．

以下の画像は Firefox 48.0.1 での動作例である．

<img width="720" alt="jay_txt_download_link_03" src="https://cloud.githubusercontent.com/assets/7124058/18152306/cf346460-702f-11e6-8378-ffbaab8ef9da.png">
